### ISSUE TITLE
sitemaps in custom folders not copied over

### ISSUE THREAD

**Issue by chanko** [lassebunk/dynamic_sitemaps#10]
I set a folder before defining a sitemap, and I can see the sitemap file in the correct folder being generated in the tmp/dynamic_sitemaps. 

Once the rake task finishes and copies the files over to the appropriate folder in public, I see the custom folders, but they're always empty.

Any ideas?

**Comment by lassebunk** [comment]
Thanks for bringing this up. Could you post your `config/sitemap.rb` here or as a gist?
Thanks.

**Comment by chanko** [comment]
Sure.

https://gist.github.com/chanko/068c2ea84301a665f24e

Thanks!

**Comment by lassebunk** [comment]
Fixed and tested in 2.0.0. Thanks for the info.
