### ISSUE TITLE
config/initializers/sitemap.rb:1:in `<top (required)>': undefined method `draw' for DynamicSitemaps::Sitemap:Class (NoMethodError)

### ISSUE THREAD

**Issue by numanilyas** [lassebunk/dynamic_sitemaps#13]
I am having this error today:
config/initializers/sitemap.rb:1:in `<top (required)>': undefined method`draw' for DynamicSitemaps::Sitemap:Class (NoMethodError)

If I revert to my two day earlier release then it works fine.

**Comment by lassebunk** [comment]
Yeah, the 2.0 DSL is somewhat incompatible with the 1.x one, because it uses another approach to generating sitemaps, giving support for larger sitemaps. If you have a large sitemap, I recommend upgrading your config (see the readme). Else just use this in your Gemfile:

``` ruby
gem "dynamic_sitemaps", "1.0.8"
```

**Comment by numanilyas** [comment]
thanks, version 1.0.8 is working fine for me.

**Comment by lassebunk** [comment]
Ok super. :+1:
