### ISSUE TITLE
Subdomains

### ISSUE THREAD

**Issue by napster3000** [lassebunk/dynamic_sitemaps#17]
I have this object

Movies
ID, Title, Country

Now I have to every url to a movie be like:

http://uk.example.com/movies/32

and this refer to movie (ID=32 and country=uk). How is that possible?

I tried something like this, but doesn't work

sitemap_for Program.all do |p|
    url p, host: "#{p.country}.test.com"
end

**Comment by napster3000** [comment]
sitemap_for Movie.all do |m|
    url movie_url(m, subdomain: m.country)
   end

**Comment by lassebunk** [comment]
Hi,

As the readme says:

> The argument passed to sitemap_for needs to respond to #find_each, like an ActiveRecord Relation. This is to ensure that the records from the database are lazy loaded 1,000 at a time, so that it doesn't accidentally load millions of records in one call when the configuration file is read. Therefore we use Page.scoped instead of the normal Page.all.

So you need to do `sitemap_for Movie.scoped` instead.

**EDIT:** Ah, you're using Rails 4 so `#all` returns a relation. :blush:
