### ISSUE TITLE
A sitemap for each domain

### ISSUE THREAD

**Issue by napster3000** [lassebunk/dynamic_sitemaps#18]
I have these subdomains

http://uk.zapping.io
http://italy.zapping.io

Now, I have to separate each sitemap for each subdomain

When I generate my sitemap I do this

   sitemap_for Program.all do |p|
      subdomain = Something()
      url program_url(p, subdomain: subdomain), last_mod: p.updated_at
   end

and it generate all urls for all subdomains.

<url>
<loc>http://uk.zapping.io/programs/3-the-chronicles-of-narnia-prince-caspian</loc>
<lastmod>2013-12-29T21:48:55+00:00</lastmod>
</url>

 Is there a way to get multiple sitemaps?
This is because I will submit each sitemap to a different site on Google Webmaster

**Comment by lassebunk** [comment]
Yes, check the readme: https://github.com/lassebunk/dynamic_sitemaps#production-example-with-multiple-domains-capistrano-and-whenever

Btw, your icons on zapping.io don't work in Firefox – maybe because of CORS.
