### ISSUE TITLE
Sitemap doesn't work

### ISSUE THREAD

**Issue by MaximeRVY** [lassebunk/dynamic_sitemaps#2]
Hello, 

Thanks for this plugin.  
But something are strange, when I add this line : "per_page 10" or "new_page!",  I have just the last line to my sitemap.
But I wish see this : 

<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">

   <sitemap>

```
  <loc>http://www.example.com/sitemap1.xml.gz</loc>

  <lastmod>2004-10-01T18:23:17+00:00</lastmod>
```

   </sitemap>

   <sitemap>

```
  <loc>http://www.example.com/sitemap2.xml.gz</loc>

  <lastmod>2005-01-01</lastmod>
```

   </sitemap>

</sitemapindex>

How can  I have this ? 

Thanks a lot.

**Comment by lassebunk** [comment]
Maxime, you mention that you "have just the last line to my sitemap". Could you please post that line here?

/Lasse

**Comment by MaximeRVY** [comment]
I puts this : 
new_page!
    Category.roots.each do |category|
      if category.catalog_published
        url item_show_category_url(:permalink => category.permalink), :last_mod => DateTime.now, :change_freq => "weekly", :priority => 0.7
        category.children.where(:catalog_published => true).each do |sub_category|
          url item_show_child_category_url(:permalink => category.permalink, :child_permalink => sub_category.permalink), :last_mod => DateTime.now, :change_freq => "weekly", :priority => 0.7
        end
      end
    end

But I have this before :
url root_url, :last_mod => DateTime.now, :change_freq => 'daily', :priority => 1

And it's not in my sitemap.xml. I don't understand why. 

Thanks for your answer

**Comment by lassebunk** [comment]
I think it's because it splits your sitemap up into two files, or "pages" with the `new_page!` method. Then _sitemap.xml_ will contain two references; one to _sitemap.xml?page=1_ and _sitemap.xml?page=2_.
Does this answer your question?
