### ISSUE TITLE
HTTPS protocol

### ISSUE THREAD

**Issue by cannuk** [lassebunk/dynamic_sitemaps#20]
I see that the overall protocol of links generated is set to `http`. I need to allow for https links.  My thought was to allow you to set `protocol` in config and default it to `http`. Thoughts?

**Comment by cannuk** [comment]
Pull request, allows you to set the protocol in the configuration file
https://github.com/lassebunk/dynamic_sitemaps/pull/21

**Comment by alvarezm50** [comment]
HTTPs support +1

**Comment by kuzevanoff** [comment]
NoMethodError: undefined method `protocol=' for DynamicSitemaps:Module
config/sitemap.rb
DynamicSitemaps.configure do |config|
  config.protocol = "https"
end
