### ISSUE TITLE
Allow alternate language

### ISSUE THREAD

**Issue by GCorbel** [lassebunk/dynamic_sitemaps#29]
Hi,

I'm looking for a way to add [this behavior](ashttps://support.google.com/webmasters/answer/2620865?hl=en). I think it can be useful to change the code to add this possibility.

Thanks!

**Comment by lassebunk** [comment]
Thanks for writing, @GCorbel.
Can you explain a little further?

**Comment by GCorbel** [comment]
I have a bilingual website and I want to say to Google than one page is in english and another is in french. I forgot to add the link on my previous comment : https://support.google.com/webmasters/answer/2620865?hl=en .

**Comment by lassebunk** [comment]
Okay. Any chance you could put together a pull request for this?
Alternatively, you could create two sitemaps, one for each language, using the `folder` directive. See the [readme](https://github.com/lassebunk/dynamic_sitemaps#sitemap-setup) for an example.

**Comment by GCorbel** [comment]
Ok but how can I use a specific folder for a locale?

**Comment by lassebunk** [comment]
Depending on your localization setup, e.g. in _config/sitemap.rb_:

``` ruby
I18n.available_locales.each do |locale|
  folder "sitemaps/#{locale}"
  url root_url
  # etc
end
```

Or, if you have localized routes:

``` ruby
I18n.available_locales.each do |locale|
  I18n.with_locale(locale) do
    url root_url
    # etc
  end
end
```

**Comment by GCorbel** [comment]
I don't know if it's better to specify the locale in the sitemap. I can specify in the head tag also.

**Comment by lassebunk** [comment]
Yes. Without knowing too much about the best practice here, I'd just put it in the head tag. Google recognizes this when they crawl.

**Comment by GCorbel** [comment]
Ok, that's I will do.

**Comment by GCorbel** [comment]
I forgot to say a big thanks for the fast answer!

**Comment by lassebunk** [comment]
No problem :) Hope it helped!
