### ISSUE TITLE
Doesn't seem to be working with Rails 4.2.3 / Ruby 2.2.2

### ISSUE THREAD

**Issue by marvindanig** [lassebunk/dynamic_sitemaps#38]
I do see that the gem hasn't been updated for past two years, but it was working until 4.1.6. I believe it stopped working after I upgraded to 4.2.3, but then is anyone else facing this issue?

**Comment by GringoDotDev** [comment]
@marvindanig was checking out this gem - did you ever get it to work on Rails 4.2+?

**Comment by marvindanig** [comment]
@jseitel nope... I don't remember exactly but I think we used [sitemap_generator](https://github.com/kjvarga/sitemap_generator) gem instead.

**Comment by GringoDotDev** [comment]
@marvindanig Thanks for the update.  I ended up just building one with a standard Rails controller.  Once I read the sitemap spec I realized it was pretty easy for small sites. :)
