### ISSUE TITLE
times

### ISSUE THREAD

**Issue by Unpakt** [lassebunk/dynamic_sitemaps#9]
When I submitted my sitemap to Google, it complained about the time formats. The format should be 'yyyy-mm-dd'. Can you either turn a Date or Time object into the correct the correct format, or update the wiki page to stress this?

Thanks

**Comment by lassebunk** [comment]
Hi Unpakt :-)

Thanks for observing this problem.
Could you supply a pull request to fix it?

Thanks in advance :-)
/Lasse

**Comment by lassebunk** [comment]
@Unpakt Any news on this? :-)

/Lasse

**Comment by lassebunk** [comment]
Fixed in 2.0.0.
